# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
  # `.` or absolute path, please note that the directories following must be under root.
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Just plain old shell command. You could use `make` as well.
  args_bin = []
  # Binary file yielded from `cmd`.
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/web"
  # It's not necessary to trigger build each time file changes if it's too frequent.
  delay = 1000
  # Ignore these filename extensions or directories.
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "frontend/node_modules"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  follow_symlink = true
  full_bin = "./tmp/main"
  include_dir = []
  # Watch these filename extensions.
  include_ext = ["go", "tpl", "tmpl", "html", "css"]
  include_file = []
  kill_delay = "0s"
  log = "air.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  # Send Interrupt signal before killing process (windows does not support this feature)
  send_interrupt = true
  # Stop running old binary when build errors occur.
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  # Delete tmp directory on exit
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
